<?php
/**
 * TL_ROOT/system/modules/multilingualelements/languages/ru/default.php 
 * 
 * Contao extension: multilingualelements 0.9.1 
 * Russian translation file 
 * 
 * Copyright : &copy; 2015 Arne Stappen 
 * License   : LGPL-3.0+ 
 * Author    : aGoat (agoat), http://agoat.de 
 * Translator: Dmitri Kuznetsov (Kuzmich) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['multilingualelements'] = "Многоязычные статьи и элементы контента";
 
?>
