<?php
/**
 * TL_ROOT/system/modules/multilingualelements/languages/ru/tl_module.php 
 * 
 * Contao extension: multilingualelements 0.9.1 
 * Russian translation file 
 * 
 * Copyright : &copy; 2015 Arne Stappen 
 * License   : LGPL-3.0+ 
 * Author    : aGoat (agoat), http://agoat.de 
 * Translator: Dmitri Kuznetsov (Kuzmich) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['language']['0'] = "Язык модуля";
$GLOBALS['TL_LANG']['tl_module']['language']['1'] = "Введите язык модуля согласно стандарта ISO-639-1 (напр. \"en\"для английского или \"en-US\" для американского английского языка). Оставьте пустым, чтобы показать модуль для всех языков. Базовым будет язык корневой страницы.";
 
?>
